version: '3'

services:
  nginx:
    image: nginx
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./cors.conf:/etc/nginx/conf.d/default.conf:ro
      - ./gzip.conf:/etc/nginx/conf.d/gzip.conf      
      - .:/usr/share/nginx/html:ro
    networks:
      - default
      - www

networks:
  www:
    external:
      name: www
