name: Indexes

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Check ENABLE_ACTIONS
        env:
          ENABLE_ACTIONS: ${{ secrets.ENABLE_ACTIONS }}
        run: if [ "$ENABLE_ACTIONS" != "yes" ]; then exit 1; fi

      # Setup:

      - name: Checkout files
        uses: actions/checkout@v2

      - name: Checkout scripts
        uses: actions/checkout@v2
        with:
          repository: natureshare/natureshare-scripts
          path: _scripts

      # Install:

      - name: NPM Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-npm
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: NPM Install
        run: |
          cd _scripts
          npm ci

      # Run:

      - name: Validate
        env:
          CONTENT_FILE_PATH: ../
          SECRETS_JSON: ${{ toJSON(secrets) }}
        run: |
          cd _scripts
          time node validator/run.js

      - name: Indexes
        env:
          CONTENT_FILE_PATH: ../
          SECRETS_JSON: ${{ toJSON(secrets) }}
        run: |
          cd _scripts
          time node indexes/items.js
          time node indexes/collections.js
          time node indexes/users.js

      # Deploy:

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: .
          CLEAN: true
          SINGLE_COMMIT: true
