name: Validate

on:
  workflow_dispatch:
    
  # push:
  #   branches:
  #     - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Setup:

      - name: Checkout files
        uses: actions/checkout@v2
        with:
          path: files

      - name: Checkout scripts
        uses: actions/checkout@v2
        with:
          repository: natureshare/natureshare-web
          path: web

      # Install:
      
      - name: NPM Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-npm
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
              
      - name: NPM Install
        run: |
          cd web
          npm ci

      # Run:

      - name: Validate files
        env:
          CONTENT_FILE_PATH: ../files
        run: |
          cd web
          node scripts/validate.js
